version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lazylore
    main: ./cmd/lazylore
    binary: lazylore
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: lazylore
    ids:
      - lazylore
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  github:
    owner: Solessfir
    name: lazylore

winget:
  - name: lazylore
    package_identifier: Solessfir.lazylore
    publisher: Solessfir
    short_description: A terminal UI for Lore.
    license: MIT
    homepage: https://github.com/Solessfir/lazylore
    license_url: "https://github.com/Solessfir/lazylore/blob/{{ .Tag }}/LICENSE"
    publisher_support_url: https://github.com/Solessfir/lazylore/issues
    skip_upload: auto
    commit_msg_template: "Update {{ .PackageIdentifier }} to {{ .Version }}"
    repository:
      owner: Solessfir
      name: winget-pkgs
      branch: "lazylore-{{ .Version }}"
      token: "{{ .Env.WINGET_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master
